<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="imageslidertest.aspx.cs" Inherits="CarebookPro.imageslidertest" %>

<%@ Register Assembly="DevExpress.Web.v17.1, Version=17.1.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" Namespace="DevExpress.Web" TagPrefix="dx" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <dx:ASPxImageSlider ID="ASPxImageSlider1" runat="server" SeoFriendly="True" Theme="Material" Width="1437px">
            <SettingsImageArea AnimationType="Fade" EnableLoopNavigation="True" />
            <SettingsNavigationBar Mode="Dots" />
            <SettingsSlideShow AutoPlay="True" PlayPauseButtonVisibility="Always" />
            <SettingsAutoGeneratedImages ImageCacheFolder="~/Thumb/" />
            <Styles>
                <ImageArea Border-BorderStyle="None">
                </ImageArea>
                <NavigationBarDotsModeBottom BackColor="#08363B">
                </NavigationBarDotsModeBottom>
                <NavigationBarDotsModeLeft BackColor="#08363B">
                </NavigationBarDotsModeLeft>
                <Dot BackColor="#08363B" Border-BorderStyle="None">
                </Dot>
            </Styles>
            <Items>
                <dx:ImageSliderItem ImageUrl="Images/gettyimages-634818722-1545171533.png">
                </dx:ImageSliderItem>
                <dx:ImageSliderItem ImageUrl="Images/gettyimages-859992816-1545174069.png">
                </dx:ImageSliderItem>
                <dx:ImageSliderItem ImageUrl="Images/gettyimages-859992816-1545174069.png"  >
                </dx:ImageSliderItem>
            </Items>
        </dx:ASPxImageSlider>
    </div>
    </form>
</body>
</html>
